import { useCallback, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect } from "expo-router/react-navigation";
import { useRouter } from "expo-router";
import { ArrowLeft, ShieldCheck } from "lucide-react-native";
import { getSystemSecurityPinStatus, resetSystemSecurityPin, saveSystemSecurityPin } from "../../src/api/saasApi";
import { systemColors as colors } from "../../src/theme/systemTheme";

const isPin = (value) => /^\d{4,8}$/.test(value);
export default function SystemSecurityScreen() {
  const router = useRouter(); const [configured,setConfigured]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [pin,setPin]=useState(""); const [confirm,setConfirm]=useState(""); const [current,setCurrent]=useState(""); const [password,setPassword]=useState(""); const [reset,setReset]=useState(false);
  const load=useCallback(async()=>{try{const data=await getSystemSecurityPinStatus();setConfigured(Boolean(data.configured));}catch(err){Alert.alert("Unable to load security",err.response?.data?.message||"Please try again.");}finally{setLoading(false);}},[]); useFocusEffect(useCallback(()=>{load();},[load]));
  const digits=(value,setter)=>setter(value.replace(/\D/g,"").slice(0,8));
  async function save(){if(!isPin(pin))return Alert.alert("Invalid PIN","Use a 4 to 8 digit PIN.");if(pin!==confirm)return Alert.alert("PINs do not match","Enter the same PIN twice.");if(configured&&!reset&&!isPin(current))return Alert.alert("Current PIN required","Enter your current security PIN.");if(reset&&!password)return Alert.alert("Password required","Enter your account password to reset the PIN.");try{setSaving(true);if(reset)await resetSystemSecurityPin({pin,password});else await saveSystemSecurityPin({pin,currentPin:current});setConfigured(true);setReset(false);setPin("");setConfirm("");setCurrent("");setPassword("");Alert.alert("Security PIN saved","Your PIN is now required before deleting data.");}catch(err){Alert.alert("Unable to save PIN",err.response?.data?.message||"Please try again.");}finally{setSaving(false);}}
  if(loading)return <View style={s.loading}><ActivityIndicator size="large" color={colors.primary}/></View>;
  return <ScrollView style={s.screen} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><ArrowLeft size={24} color={colors.text}/></Pressable><View><Text style={s.eyebrow}>ACCOUNT SECURITY</Text><Text style={s.title}>Security PIN</Text></View></View><View style={s.hero}><ShieldCheck size={34} color={colors.primary}/><Text style={s.heroTitle}>{configured?"Security PIN enabled":"Protect deletions"}</Text><Text style={s.heroText}>Your PIN is required before deleting tenants, units, beds, bills and expenses.</Text></View><View style={s.card}>{configured&&!reset?<><Text style={s.label}>Current security PIN</Text><TextInput value={current} onChangeText={v=>digits(v,setCurrent)} keyboardType="number-pad" secureTextEntry maxLength={8} style={s.input}/><Pressable onPress={()=>{setReset(true);setCurrent("");}}><Text style={s.link}>Forgot PIN? Reset using account password</Text></Pressable></>:reset?<><Text style={s.hint}>Confirm your account password to reset your PIN.</Text><Text style={s.label}>Account password</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry style={s.input}/></>:null}<Text style={s.label}>New security PIN</Text><TextInput value={pin} onChangeText={v=>digits(v,setPin)} keyboardType="number-pad" secureTextEntry maxLength={8} placeholder="4 to 8 digits" style={s.input}/><Text style={s.label}>Confirm security PIN</Text><TextInput value={confirm} onChangeText={v=>digits(v,setConfirm)} keyboardType="number-pad" secureTextEntry maxLength={8} style={s.input}/><Pressable onPress={save} disabled={saving} style={s.save}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.saveText}>{configured?"Update PIN":"Set security PIN"}</Text>}</Pressable></View></ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.screen},content:{padding:18,paddingBottom:42},loading:{flex:1,alignItems:"center",justifyContent:"center"},header:{minHeight:58,flexDirection:"row",alignItems:"center",gap:10},back:{width:42,height:42,alignItems:"center",justifyContent:"center"},eyebrow:{fontSize:11,fontWeight:"900",color:colors.primary},title:{fontSize:26,fontWeight:"900",color:colors.text},hero:{marginTop:12,padding:18,borderRadius:16,backgroundColor:colors.primarySoft},heroTitle:{marginTop:10,fontSize:18,fontWeight:"900",color:colors.text},heroText:{marginTop:5,lineHeight:20,color:colors.muted},card:{marginTop:14,padding:16,borderRadius:16,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},label:{marginTop:13,marginBottom:7,color:colors.text,fontWeight:"800"},input:{height:50,paddingHorizontal:13,borderWidth:1,borderColor:colors.border,borderRadius:10,color:colors.text,fontSize:16},link:{marginTop:11,color:colors.primary,fontWeight:"800"},hint:{color:colors.muted},save:{height:52,marginTop:22,alignItems:"center",justifyContent:"center",borderRadius:12,backgroundColor:colors.primary},saveText:{color:"#fff",fontSize:16,fontWeight:"900"}});
